### ISSUE TITLE
relaxation frequency; fracture; thickness

### ISSUE THREAD

**Issue by MiniSkull** [seismology-RUB/NEXD-2D#1]
Hi!
Thanks for developing such a great software so I can use it for simulating seismic wave propagation in fractured rock.
I am still learning to use the software. I have two questions that confuse me a lot.

Q1:
To take a fracture into consideration, normal and tangential relaxation frequencies defined in _interfaces_ file are necessary in the software.
In rock mechanics,  a normal and tangential stiffness (MPa/m) is usually used to define the mechanical properties of a fracture. And an aperture (thickness) is assigned to the fracture. 
Is there any relationship between relaxation frequency and stiffness (elastic modulus, thickness, etc.)?
Is it possible that if we know elastic modulus, thickness, or stiffness of a fracture, we can know relaxation frequency?

Q2:
I make a simple model to simulate seismic wave propagation in a 5 m* 5 m domain size.
There are several fractures in the domain with two same relaxation frequencies 100 Hz.
A source with a Ricker wavelet with a center frequency of 50 Hz is located at x, y =2.0, 5.0.
A receiver is located at x, y = 3.0, 5.0.
I did not see any reflected waves from fractures at the receiver. Only a direct wave from the source was observed. 
When I increased the center frequency from 50 Hz to 200 Hz. Reflected waves from fractures can be observed.
If I want to get reflected waves from fractures when a source with a frequency of 50 Hz, how should I do?

Thanks!
Best regards,
Jin

**Comment by tommyM86** [comment]
Hi Jin,
Thank you for your interest in our Code!

Regarding your questions:
Q1: Yes, such a relation exists. A description of how we formulated that relation can be found in my dissertation in Chapter 2.1.2. You can find my dissertation [here](https://www.researchgate.net/publication/327051809_Numerical_modelling_of_seismic_wave_propagation_in_fractured_media_for_the_characterization_of_geothermal_reservoirs).

Q2: Without knowing your model setup in detail I can only speculate here. Could you send me the files characterizing your model, source, and receiver setup and how the fractures a placed? 

Best regards
Thomas

**Comment by MiniSkull** [comment]
@tommyM86
Thanks so much for your answers.
The attached compressed file includes my model information. Please have a check.
I placed a fracture horizontally in the domain. I changed the source frequency from 50 Hz to  500 Hz. It seems that there is no reflected waves received by a receiver.

Thanks!
Best regards,
Jin

**Comment by MiniSkull** [comment]
@tommyM86
Thanks so much for your answers.
The attached compressed file includes my model information. Please have a check.
https://1drv.ms/u/s!Ai9GL0b0X-SHgZM6UEwmP9G5WNq1fw?e=GfENYF

I placed a fracture horizontally in the domain. I changed the source frequency from 50 Hz to 500 Hz. It seems that there is no reflected waves received by a receiver.

Thanks!
Best regards,
Jin

**Comment by tommyM86** [comment]
Hi Jin, 

first of all, I am sorry for not getting back to you sooner. I was on vacation for the past two weeks.

Regarding your model: I ran the simulation with the parameters given in the parameter file you provided (200 Hz wavelet, 100 Hz fracture). What you see at the receiver is actually a combination of the direct and reflected wave. Due to the very small dimensions of the model (in comparison to the material and source properties), it seems that you only see the direct waves and not the reflected wave, but they simply overlap. The differences in travel time are too short to distinguish both waves. 
If you want to keep the material values and the parameter for source and fracture, you may want to increase the size of the model significantly. I would suggest at least a factor of 10, better 100.   

Best regards,
Thomas
