### ISSUE TITLE
NEXD-2D; full waveform inversion; Segmentation fault

### ISSUE THREAD

**Issue by MiniSkull** [seismology-RUB/NEXD-2D#2]
Hi!
I am really sorry to bother you again.
Recently, I have been learning to use the full waveform inversion function in NEXD-2D.
I can run an benchmark example which is provided in _NEXD-2D\simulations\example_inversion_ without any error. 
However, I got an error  when I did a FWI simulation using my own model.
It was quite weird!
The error is _Program received signal SIGSEGV: Segmentation fault - invalid memory reference_.
_process.sh: line 41: 11162 Segmentation fault      (core dumped) ./bin/mesher_
I can run a forward simulation without any error. But I did not succeed in making an inversion simulation.
I thought it was because of mask_radius set in the _parfile_. But I changed it from a smaller to a larger value, the error still existed.
I checked _out_ folder. The files (e.g.,  mask.vtk, meshVar00000*) do not exist. 
I tried to change many parameters in the _parfile_ without success.

Can you have a check my model when you are not busy?
https://1drv.ms/u/s!Ai9GL0b0X-SHgZM-4S0VDeilRNK6wg?e=6YwuMe

Thanks!
Best regards,
Jin

**Comment by alamert** [comment]
Hi Jin,

thank you for your message. There was indeed a small bug in the code leading to a segmentation fault in some cases when using the inversion function. We updated the code so that the bug should not appear again. Please download the new version 0.4.1. I run the mesher on your example without an error. 

When I was checking your example I noticed that you are using the adjoint inversion and the linear slip interfaces (LSI) at the same time. As mentioned in the manual we do not recommend to do that. We cannot guarantee that the code runs properly in this mode and that the results of the adjoint simulations with the LSI are physically reliable. 
It is of course possible to create synthetic measurements with the LSI which are to be reconstructed during the inversion. But in this case one should have in mind that the fractures will be reconstructed as material contrasts on the level of elements and not as interfaces on the element edges.

Best regards,

Andre

**Comment by MiniSkull** [comment]
Thanks for your great help!!! Now it works.

Also, thanks for pointing out the potential issue when the adjoint inversion and LSI work at the same time.
I will check the result carefully.

Best regards,
Jin


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
